### ISSUE TITLE
Patching doesn't work

### ISSUE THREAD

**Issue by migzai** [ds300/patch-package#11]
When patch-package is run.. the target files remain intact.  I did some debugging and it turns out that 'git apply -v file.patch' is skipping patches.

**Skipped patch 'node_modules/react-native-ssdp/lib/client.js'.
Skipped patch 'node_modules/react-native-ssdp/lib/index.js'.
Skipped patch 'node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js'.**

Not sure why.  This happens on Windows and MacOS.

**Comment by ds300** [comment]
Thanks for the report. Do you mind sharing your patch files so I can debug this?

**Comment by migzai** [comment]
Sure.  Attached the patch file.

[react-native-ssdp+2.7.5.zip](https://github.com/ds300/patch-package/files/1244543/react-native-ssdp.2.7.5.zip)

**Comment by ds300** [comment]
Cool thanks. I'm quite busy until Saturday but will try to make soke time to look at this before then, it's a high priority for me.

**Comment by ds300** [comment]
Looks like it might be related to patching nested dependencies.

@migzai can you run 

    patch -p1 -i patches/react-native-ssdp+2.7.5.patch --verbose --dry-run

on MacOS and paste the output here please?

**Comment by migzai** [comment]
Here's the output of `patch -p1 -i patches/react-native-ssdp+2.7.5.patch --verbose --dry-run`

```
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/node_modules/react-native-ssdp/lib/client.js b/node_modules/react-native-ssdp/lib/client.js
|index 942b3f0..74c429d 100644
|--- a/node_modules/react-native-ssdp/lib/client.js
|+++ b/node_modules/react-native-ssdp/lib/client.js
--------------------------
Patching file node_modules/react-native-ssdp/lib/client.js using Plan A...
Hunk #1 succeeded at 50.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/node_modules/react-native-ssdp/lib/index.js b/node_modules/react-native-ssdp/lib/index.js
|index b90feb7..39905be 100644
|--- a/node_modules/react-native-ssdp/lib/index.js
|+++ b/node_modules/react-native-ssdp/lib/index.js
--------------------------
Patching file node_modules/react-native-ssdp/lib/index.js using Plan A...
Hunk #1 succeeded at 11.
Hunk #2 succeeded at 135.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js b/node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js
|index 73dca9f..d30bcd1 100644
|--- a/node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js
|+++ b/node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js
--------------------------
Patching file node_modules/react-native-ssdp/node_modules/react-native-udp/UdpSocket.js using Plan A...
Hunk #1 succeeded at 83.
done
```

**Comment by ds300** [comment]
Thanks. Looks fine. Must be git-specific then. Any chance you could share your repo with me? Would make it a lot easier to debug.

**Comment by migzai** [comment]
Attached a test case.. 

[test.zip](https://github.com/ds300/patch-package/files/1245378/test.zip)

**Comment by migzai** [comment]
Yes this happens if the project uses git or in case it does, the .git folder isn't at the same level as the patches directory.

**Comment by ds300** [comment]
Can confirm. Thanks. Will look into options. This project was using the unix `patch` command up until recently. We switched to `git apply` for the windows support, but it seems that introduces its own problems. On initial inspection of `git-apply`, there doesn't seem to be a cli option to work around this. Will have to look into some other option for windows.

As a temporary workaround, version 3.3.1 should work on windows with git bash.

**Comment by ds300** [comment]
I think I've fixed this now

**Comment by ds300** [comment]
I think I've fixed this now in version 3.3.4, by using the --unsafe-paths option to `git apply` Could you check it works on your end, @migzai ? I don't have Windows testing facilities.

**Comment by migzai** [comment]
I can confirm that this doesn't work on Windows still.  Git is 'Skipping patches'.

**Comment by ds300** [comment]
💩 I'll look in to this some more on saturday

**Comment by migzai** [comment]
Hi.  Any progress on this so far?  Thanks

**Comment by ds300** [comment]
Sorry I didn't make any useful progress on it yesterday. I'll have some time this evening to try again.

**Comment by ds300** [comment]
Progress update: this is definitely an inconsistency in the way `git apply` works on different platforms. Windows git ignores the facet of --unsafe-paths that says the files don't have to be in the index, and will silently skip them if it can't find them in the index. Apparently there is an  undocumented --no-index flag, but that doesn't seem to help either, at least on the windows machine I'm using. I'm going to do two things:

- check for silently skipped files
- if files were silently skipped and we're running on windows and the git root folder is not the same as the package.json, make a copy of the patch file with the named file paths resolved relative to the root of the git repo, and apply that instead.
- otherwise throw an error

This should be a forwards-compatible workaround, in case windows git ever aligns its behaviour across platforms.

**Comment by ds300** [comment]
:confused: Now I'm seeing the same behaviour on MacOS so it must be that my testing env was not set up properly when I thought I'd fixed it last week. At least that means git is consistent :)

**Comment by ds300** [comment]
@migzai Pretty sure this is fixed now. Tested on windows and everything! Do you mind confirming 3.3.5 solves your issue?

**Comment by migzai** [comment]
Hi.  Just tested 3.3.5 on Windows.  Still getting the same behavior as before..

**Comment by ds300** [comment]
😧 Even with the test repo you attached?

**Comment by migzai** [comment]
Yes..

**Comment by ds300** [comment]
My apologies. I'll double check my tests next time I have access to the windows laptop, which will be on Sunday. Sorry again for the inconvenience. Could have sworn this was working 😕

**Comment by calvin337** [comment]
Same issue here, works on node modules in the same folder as where the .git folder is but doesn't work for any sub-directories.

**Comment by ds300** [comment]
Thanks @calvin337 — is that also for windows?

**Comment by calvin337** [comment]
Yeah also for Windows, it works fine on Mac.

**Comment by ds300** [comment]
@migzai @calvin337 just released 3.3.6 - again pretty sure this fixes the issue. Third time's a charm 🤞 :D

**Comment by migzai** [comment]
I can confirm that this now works on Windows.  Thanks! There's an issue though on Linux when I attempt to run patch-package:

    Patch was made for version 0.10.8
    Meanwhile node_modules/react-native-fetch-blob is version 0.10.8

Something not logical going on and the patch-package fails with exit code 1.
[patch-package.zip](https://github.com/ds300/patch-package/files/1273734/patch-package.zip)

**Comment by ds300** [comment]
Thanks for the log. I'll take a look tonight.

**Comment by ds300** [comment]
Can't reproduce this issue on ubuntu with the test repo. @migzai  any chance you could zip and attach the patch file for react-native-fetch-blob?

**Comment by migzai** [comment]
There you go.
[react-native-fetch-blob+0.10.8.zip](https://github.com/ds300/patch-package/files/1276158/react-native-fetch-blob.0.10.8.zip)

**Comment by ds300** [comment]
Thanks. Still can't reproduce the issue with your test repo, unfortunately. I added the patch file into the patches directory, upgraded patch-package, and added react-native-fetch-blob. The patch was applied as expected on Ubuntu 17.04 with Git 2.11.0

Which linux/git are you on? Did you try deleting node_modules and trying again? Any other help you could give to reproduce the issue would be most appreciated 🙇

**Comment by ds300** [comment]
@migzai Not sure if you're still suffering from this problem, but thanks to #21 we figured out that git can enforce particular whitespace rules for patch files, which should make them work across platforms seamlessly. 🤞

All you need to do is add one line in `.gitattributes`, see the linked issue for details. Let me know if that solves your problem, or maybe you're not using patch-package anymore in which case feel free to ignore this and I'll close the issue due to inactivity in a few days.

Thanks for your help and collaboration!

**Comment by ds300** [comment]
Closing due to inactivity, as discussed. Please re-open if you find the problem has not been solved.
