### ISSUE TITLE
Can't patch package

### ISSUE THREAD

**Issue by potatoengineer** [ds300/patch-package#300]
Just installed patch-package@6.4.6 and modified my package in node_modules and tried to run `npx patch-package lottie-react-native` but ended up with error.

```
npx patch-package lottie-react-native
patch-package 6.4.6
• Creating temporary folder
• Installing lottie-react-native@3.5.0 with npm
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17928,
  stdout: null,
  stderr: null,
  error: null
}

/Users/name/folder/appName/node_modules/patch-package/dist/makePatch.js:218
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17928,
  stdout: null,
  stderr: null,
  error: null
}
```

**Comment by ds300** [comment]
Thanks for the report! ❤️ 

Fixed in https://github.com/ds300/patch-package/releases/tag/v6.4.7

**Comment by lucaszhu2zgf** [comment]
still get the same error at v6.4.7
----------------------------------
patch-package 6.4.7
• Creating temporary folder
• Installing ant-design-vue@2.1.6 with npm
{
  status: 254,
  signal: null,
  output: [ null, null, null ],
  pid: 38727,
  stdout: null,
  stderr: null,
  error: null
}

/Users/zhuguifeng/Documents/webank/init/node_modules/patch-package/dist/makePatch.js:218
        throw e;
        ^
{
  status: 254,
  signal: null,
  output: [ null, null, null ],
  pid: 38727,
  stdout: null,
  stderr: null,
  error: null
}

**Comment by magicwenli** [comment]
> ## still get the same error at @v6.4.7 @ds300
> patch-package 6.4.7
> • Creating temporary folder
> • Installing ant-design-vue@2.1.6 with npm
> {
> status: 254,
> signal: null,
> output: [ null, null, null ],
> pid: 38727,
> stdout: null,
> stderr: null,
> error: null
> }
> 
> /Users/zhuguifeng/Documents/webank/init/node_modules/patch-package/dist/makePatch.js:218
> throw e;
> ^
> {
> status: 254,
> signal: null,
> output: [ null, null, null ],
> pid: 38727,
> stdout: null,
> stderr: null,
> error: null
> }

I met it when doing `npx patch-package showdown-highlight `

**Comment by joeldenning** [comment]
I still see this with patch-package@6.4.7. I ran `pnpm exec patch-package vue-router` and got the error with status 1

**Comment by AlonsoSalas** [comment]
Same error with "patch-package": "^6.4.7". I ran `npx patch-package @strapi/admin` and I got 
```
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22699,
  stdout: null,
  stderr: null,
  error: null
}

/Users/alonsosalas/Globant/Cerifi/authoring/node_modules/patch-package/dist/makePatch.js:218
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22699,
  stdout: null,
  stderr: null,
  error: null
}```

**Comment by skag27** [comment]
same error with `npx patch-package export-from-json`

**Comment by Baskerville42** [comment]
The same error for `npx patch-package @react-native-community/cameraroll`
version 6.4.7

**Comment by tonyjaimep** [comment]
@Strate 
> For my case it was an error while command `npm install` running inside temporary folder

How did you get access to this error?

**Comment by Strate** [comment]
> @Strate
> 
> > For my case it was an error while command `npm install` running inside temporary folder
> 
> How did you get access to this error?

First, I installed `patch-package` to dependencies: `npm install patch-package`

Then, go to `node_modules/patch-package/dist/makePatch.js`, find lines like `spawnSafe_1.spawnSafeSync(`npm`, ["i", "--force"], {`, and change `stdio: "ignore",` to `stdio: "inherit",` or `stdio: "pipe",`.

**Comment by mwyatt896** [comment]
Ran into this same issue but with yarn instead of NPM. 

Had a yarn package I wanted to patch that had a separate dependency that was of a different version than specified in the yarn package. Yarn default behavior is to let you choose which version on to install upon yarn installation, but this was not happening in the makePatch.js file.

So per @Strate - we added stdio: "inherit" to the makePatch.js file and then patch-package'd patch-package with this change. This then bypassed the version issue when patch-package was trying to run the yarn install function in makePatch.js and allowed us to make the patch file

**Comment by deorst** [comment]
I ran into this issue trying to run `yarn patch-package <package_name>` in `vscode` terminal.
It failed, but for some reason it mac's terminal it worked fine without any changes applied to `patch-package`.
I checked and the `node` and `yarn` versions were same between both terminals.

**Comment by AdamZaczek** [comment]
In case you find this issue:
```bash
nvm use 16 && npx patch-package <package_name>
```

Happy new year!

**Comment by typenoob** [comment]
Just check if you are attempting to create file in your system path.Remember to use root identity for `npm install`/`npx patch-package `
```sudo su```

**Comment by penghuili** [comment]
> > @Strate
> > > For my case it was an error while command `npm install` running inside temporary folder
> > 
> > 
> > How did you get access to this error?
> 
> First, I installed `patch-package` to dependencies: `npm install patch-package`
> 
> Then, go to `node_modules/patch-package/dist/makePatch.js`, find lines like `spawnSafe_1.spawnSafeSync(`npm`, ["i", "--force"], {`, and change `stdio: "ignore",` to `stdio: "inherit",` or `stdio: "pipe",`.

thanks for the tip.

the reason this happens to me is, i changed the registry in `~/.npmrc` to my company's private registry, which doesn't have the library that i want to patch, and patch-package seems always read the `.npmrc` file in the root folder.

after changing the registry back to the default one (`registry=https://registry.npmjs.org/`), everything starts working.

**Comment by agfe2silver** [comment]
> > @Strate
> > > For my case it was an error while command `npm install` running inside temporary folder
> > 
> > 
> > How did you get access to this error?
> 
> First, I installed `patch-package` to dependencies: `npm install patch-package`
> 
> Then, go to `node_modules/patch-package/dist/makePatch.js`, find lines like `spawnSafe_1.spawnSafeSync(`npm`, ["i", "--force"], {`, and change `stdio: "ignore",` to `stdio: "inherit",` or `stdio: "pipe",`.

In my case, '_yarn_' does not work', but finally I chaged _yarn_ with **nvm**.
With above tip, **nvm** works fine.

**Comment by kasunprabath98** [comment]
i am using Yarn and path package v8.0.0. Still encountering this issue. Can anyone help

**Comment by quangtuan28200** [comment]
before I use yarn patch-package react-native-kochava-tracker
after use npx patch-package react-native-kochava-tracker and work now

**Comment by GhayoorUlHaq** [comment]
> > @Strate
> > > For my case it was an error while command `npm install` running inside temporary folder
> > 
> > 
> > How did you get access to this error?
> 
> First, I installed `patch-package` to dependencies: `npm install patch-package`
> 
> Then, go to `node_modules/patch-package/dist/makePatch.js`, find lines like `spawnSafe_1.spawnSafeSync(`npm`, ["i", "--force"], {`, and change `stdio: "ignore",` to `stdio: "inherit",` or `stdio: "pipe",`.

Using yarn, I also needed to remove` "--ignore-engines"` as well. So, 
replace this code  
```java
 spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
                    cwd: tmpRepoNpmRoot,
                    logStdErrOnError: false,
                });
```

to
```java
spawnSafe_1.spawnSafeSync(`yarn`, ["install"], {
                    cwd: tmpRepoNpmRoot,
                    logStdErrOnError: false,
                    stdio: "inherit",
                });
```

Thanks @Strate

**Comment by c-info** [comment]
having the same issue on Yarn and path package v8.0.0. I am still encountering this issue in Node v20.5.0.

**Comment by thakkur** [comment]
i have resolved the same issue by making patch package of patch-packages 😂
`diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
index d8d0925..a292026 100644
--- a/node_modules/patch-package/dist/makePatch.js
+++ b/node_modules/patch-package/dist/makePatch.js
@@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
                 fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
             }
         });
-        if (packageManager === "yarn") {
+        if (packageManager === "npm") {
             console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
             try {
                 // try first without ignoring scripts in case they are required
                 // this works in 99.99% of cases
-                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
+                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
                     cwd: tmpRepoNpmRoot,
                     logStdErrOnError: false,
                 });
@@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
             catch (e) {
                 // try again while ignoring scripts in case the script depends on
                 // an implicit context which we haven't reproduced
-                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
+                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
                     cwd: tmpRepoNpmRoot,
                 });
             }
`

**Comment by thakkur** [comment]
I resolved the issue by creating a patch package with `patch-package` 😂

```diff
diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
index d8d0925..a292026 100644
--- a/node_modules/patch-package/dist/makePatch.js
+++ b/node_modules/patch-package/dist/makePatch.js
@@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
                 fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
             }
         });
-        if (packageManager === "yarn") {
+        if (packageManager === "npm") {
             console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
             try {
                 // try first without ignoring scripts in case they are required
                 // this works in 99.99% of cases
-                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
+                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
                     cwd: tmpRepoNpmRoot,
                     logStdErrOnError: false,
                 });
@@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
             catch (e) {
                 // try again while ignoring scripts in case the script depends on
                 // an implicit context which we haven't reproduced
-                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
+                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
                     cwd: tmpRepoNpmRoot,
                 });
             }
```

**Comment by kingkongqn4444** [comment]
> I resolved the issue by creating a patch package for `patch-package` 😂 Patch name: patch-package+8.0.0.patch
> 
> ```diff
> diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
> index d8d0925..a292026 100644
> --- a/node_modules/patch-package/dist/makePatch.js
> +++ b/node_modules/patch-package/dist/makePatch.js
> @@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>                  fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
>              }
>          });
> -        if (packageManager === "yarn") {
> +        if (packageManager === "npm") {
>              console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
>              try {
>                  // try first without ignoring scripts in case they are required
>                  // this works in 99.99% of cases
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
>                      cwd: tmpRepoNpmRoot,
>                      logStdErrOnError: false,
>                  });
> @@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>              catch (e) {
>                  // try again while ignoring scripts in case the script depends on
>                  // an implicit context which we haven't reproduced
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
>                      cwd: tmpRepoNpmRoot,
>                  });
>              }
> ```

it worked for me, very helpful

**Comment by alimurad-1** [comment]
> > I resolved the issue by creating a patch package for `patch-package` 😂 Patch name: patch-package+8.0.0.patch
> > ```diff
> > diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
> > index d8d0925..a292026 100644
> > --- a/node_modules/patch-package/dist/makePatch.js
> > +++ b/node_modules/patch-package/dist/makePatch.js
> > @@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
> >                  fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
> >              }
> >          });
> > -        if (packageManager === "yarn") {
> > +        if (packageManager === "npm") {
> >              console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
> >              try {
> >                  // try first without ignoring scripts in case they are required
> >                  // this works in 99.99% of cases
> > -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
> > +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
> >                      cwd: tmpRepoNpmRoot,
> >                      logStdErrOnError: false,
> >                  });
> > @@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
> >              catch (e) {
> >                  // try again while ignoring scripts in case the script depends on
> >                  // an implicit context which we haven't reproduced
> > -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
> > +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
> >                      cwd: tmpRepoNpmRoot,
> >                  });
> >              }
> > ```
> 
> it worked for me, very helpful

patching the patch-package resolved the issue...thank you

**Comment by owens-ben** [comment]
> ```diff
> if (packageManager === "yarn") {
> ```

this works, but why????

**Comment by TomAtterton** [comment]
> I resolved the issue by creating a patch package for `patch-package` 😂 Patch name: patch-package+8.0.0.patch

Love a bit of patch-package inception

`yarn patch-package patch-package`

**Comment by matinzd** [comment]
![99vks1](https://github.com/user-attachments/assets/6d9046cc-1827-4c61-8470-d5be367aa230)

**Comment by LukasMod** [comment]
Got similar error with node v20.18.0, changed to node v18.18.2 and `npx patch-package` worked

**Comment by ndpiparava** [comment]
> I resolved the issue by creating a patch package for `patch-package` 😂 Patch name: patch-package+8.0.0.patch
> 
> diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
> index d8d0925..a292026 100644
> --- a/node_modules/patch-package/dist/makePatch.js
> +++ b/node_modules/patch-package/dist/makePatch.js
> @@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>                  fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
>              }
>          });
> -        if (packageManager === "yarn") {
> +        if (packageManager === "npm") {
>              console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
>              try {
>                  // try first without ignoring scripts in case they are required
>                  // this works in 99.99% of cases
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
>                      cwd: tmpRepoNpmRoot,
>                      logStdErrOnError: false,
>                  });
> @@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>              catch (e) {
>                  // try again while ignoring scripts in case the script depends on
>                  // an implicit context which we haven't reproduced
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
>                      cwd: tmpRepoNpmRoot,
>                  });
>              }

How can apply this patch ?

**Comment by TangoPJ** [comment]
> I resolved the issue by creating a patch package for `patch-package` 😂 Patch name: patch-package+8.0.0.patch
> 
> diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
> index d8d0925..a292026 100644
> --- a/node_modules/patch-package/dist/makePatch.js
> +++ b/node_modules/patch-package/dist/makePatch.js
> @@ -115,12 +115,12 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>                  fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
>              }
>          });
> -        if (packageManager === "yarn") {
> +        if (packageManager === "npm") {
>              console_1.default.info(chalk_1.default.grey("•"), `Installing ${packageDetails.name}@${packageVersion} with yarn`);
>              try {
>                  // try first without ignoring scripts in case they are required
>                  // this works in 99.99% of cases
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines"], {
>                      cwd: tmpRepoNpmRoot,
>                      logStdErrOnError: false,
>                  });
> @@ -128,7 +128,7 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
>              catch (e) {
>                  // try again while ignoring scripts in case the script depends on
>                  // an implicit context which we haven't reproduced
> -                spawnSafe_1.spawnSafeSync(`yarn`, ["install", "--ignore-engines", "--ignore-scripts"], {
> +                spawnSafe_1.spawnSafeSync(`npm`, ["install", "--ignore-engines", "--ignore-scripts"], {
>                      cwd: tmpRepoNpmRoot,
>                  });
>              }

I'ts very funny, but worked for me. Thank you! :)

**Comment by omatt** [comment]
I encountered a similar error while making a patch using patch-package 8.0.1

This is the error thrown

```
npm notice run {PROJECT}@0.0.1 npx
npm notice run 'patch-package' react-native-track-player
patch-package 8.0.1
• Creating temporary folder
• Installing react-native-track-player@4.1.2 with npm
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23308,
  stdout: null,
  stderr: null,
  error: null
}

{PROJECT_PATH}/node_modules/patch-package/dist/makePatch.js:395
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23308,
  stdout: null,
  stderr: null,
  error: null
}

Node.js v26.5.0
```

Temporarily allowing the package to fetch from remote fixed the issue for me:

```
npm config set allow-remote true
npx patch-package react-native-track-player
npm config set allow-remote false
```
