### ISSUE TITLE
please upgrade dependecy package "rimraf" to newer version as is no longer supported. 

### ISSUE THREAD

**Issue by mjalav** [ds300/patch-package#537]
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported

**Comment by sparecycles** [comment]
Note to maintainers: Looks like https://github.com/ds300/patch-package/pull/517 would address this?

**Comment by rakleed** [comment]
I guess `rimraf` should be upgraded to `4.4.1` or better to `5.0.10` because it [supports Node@14](https://github.com/isaacs/rimraf/blob/main/CHANGELOG.md#v40) and [doesn't mark as deprecated](https://www.npmjs.com/package/rimraf?activeTab=versions).

**Comment by YasharF** [comment]
Fixed with https://github.com/ds300/patch-package/commit/948585db7c44c195591a7e91401ed39570b9f7fb

**Comment by gkiely** [comment]
This hasn't been fixed (or deployed to npm) the warning is still present.

**Comment by dopenguin** [comment]
As mentioned in https://github.com/ds300/patch-package/issues/575#issuecomment-3642661818, this issue seems to be resolved as well, @mjalav 😊
